### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by ksmithut** [freemountain/fux#1]
This project looks really awesome, and I'm definitely going to give it a try this weekend. But at the moment, I would not want to recommend it out loud to my coworkers because it sounds like a pretty offensive word. Any plans to change the name?

**Comment by freemountain** [comment]
Thank you, for your feedback.
I would change the name, if you show this to your coworkers  :stuck_out_tongue_winking_eye:
But i would like to keep a reference to the animal named fox (german: fuchs).
What do you think about 'vulp'?

**Comment by ksmithut** [comment]
I like that alternative :)

**Comment by freemountain** [comment]
Cool, i will rename the project this evening

**Comment by freemountain** [comment]
Renamed to vulp :)
